# Generated by Django 3.2.9 on 2021-11-12 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('couple_network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(max_length=255)),
                ('visit_count', models.IntegerField(default=1)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='couple_network.couplenet')),
            ],
        ),
        migrations.CreateModel(
            name='DatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=1)),
                ('score', models.IntegerField()),
                ('when', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='user.profile')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='couple_network.couplenet')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='date_post.place')),
            ],
        ),
    ]
