# Generated by Django 3.2.9 on 2021-11-14 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('couple_network', '0001_initial'),
        ('date_post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('when', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daycomments', to='user.profile')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daycomments', to='couple_network.couplenet')),
            ],
        ),
    ]
