# Generated by Django 3.2.9 on 2021-11-14 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('date_post', '0002_daycomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatePostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcomments', to='user.profile')),
                ('date_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='date_post.datepost')),
            ],
        ),
    ]
