# Generated by Django 3.2.9 on 2021-12-20 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_profile_img'),
        ('date_post', '0003_datepostcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(blank=True, null=True, upload_to='post_images/%Y/%m/%d')),
                ('date_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='date_post.datepost')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='user.profile')),
            ],
        ),
    ]
