# Generated by Django 3.2.9 on 2021-12-20 12:52

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('date_post', '0004_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='content',
            field=models.ImageField(blank=True, null=True, storage=user.models.OverwriteStorage(), upload_to='post_images/%Y/%m/%d'),
        ),
    ]
