# Generated by Django 3.2.9 on 2021-11-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couple_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couplenet',
            name='created_at',
            field=models.DateField(null=True),
        ),
    ]
