# Generated by Django 3.2.9 on 2021-11-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couple_network', '0002_alter_couplenet_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couplenet',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
